const fs = require('fs');
let content = fs.readFileSync('src/App.tsx', 'utf8');

content = content.replace(
  "{canEdit && <button \n                                                                onClick={() => {\n                                                                  setEditingEpisodeId(ep.id);\n                                                                  setEditingEpisodeTitle(ep.title);\n                                                                }}\n                                                                className=\"px-3 py-1.5 bg-white border border-gold/30 text-wood/60 hover:text-cinnabar hover:border-cinnabar/30 rounded-lg text-[9px] font-bold uppercase tracking-widest transition-all flex items-center gap-2\"\n                                                              >\n                                                                <PenTool size={12} /> Sửa Tên Cảnh\n                                                              </button>",
  "{canEdit && (<button \n                                                                onClick={() => {\n                                                                  setEditingEpisodeId(ep.id);\n                                                                  setEditingEpisodeTitle(ep.title);\n                                                                }}\n                                                                className=\"px-3 py-1.5 bg-white border border-gold/30 text-wood/60 hover:text-cinnabar hover:border-cinnabar/30 rounded-lg text-[9px] font-bold uppercase tracking-widest transition-all flex items-center gap-2\"\n                                                              >\n                                                                <PenTool size={12} /> Sửa Tên Cảnh\n                                                              </button>)}"
);

content = content.replace(
  "{canDelete && <button \n                                                                onClick={(e) => {\n                                                                  e.stopPropagation();\n                                                                  if (!canDelete) { alert('Chỉ admin mới có quyền xóa!'); return; }\n                                                                  setConfirmDialog({\n                                                                    message: `Bạn có chắc chắn muốn xóa cảnh \"${ep.title}\"?`,\n                                                                    onConfirm: () => deleteSubDoc('episodes', ep.id as string)\n                                                                  });\n                                                                }}\n                                                                className=\"px-3 py-1.5 bg-white border border-gold/30 text-wood/60 hover:text-cinnabar hover:border-cinnabar/30 rounded-lg text-[9px] font-bold uppercase tracking-widest transition-all flex items-center gap-2\"\n                                                              >\n                                                                <Trash2 size={12} /> Xóa Cảnh\n                                                              </button>\n                                                              }",
  "{canDelete && (<button \n                                                                onClick={(e) => {\n                                                                  e.stopPropagation();\n                                                                  if (!canDelete) { alert('Chỉ admin mới có quyền xóa!'); return; }\n                                                                  setConfirmDialog({\n                                                                    message: `Bạn có chắc chắn muốn xóa cảnh \"${ep.title}\"?`,\n                                                                    onConfirm: () => deleteSubDoc('episodes', ep.id as string)\n                                                                  });\n                                                                }}\n                                                                className=\"px-3 py-1.5 bg-white border border-gold/30 text-wood/60 hover:text-cinnabar hover:border-cinnabar/30 rounded-lg text-[9px] font-bold uppercase tracking-widest transition-all flex items-center gap-2\"\n                                                              >\n                                                                <Trash2 size={12} /> Xóa Cảnh\n                                                              </button>)}"
);

fs.writeFileSync('src/App.tsx', content);
